#!/usr/bin/env python3
"""Job 4: emit bench/keepsets-v3/<label>-<K>/ at the winning strategy's
optimum K (and one K either side of it, from the sweep grid), in the same
file layout as v1/v2 (keep-idx.json, tokenizer.json, tokenizer_config.json,
special_tokens_map.json, config-patch.json, coverage.json, provenance.md,
SHA256SUMS.txt), carrying v2's len(AutoTokenizer.from_pretrained(dir)) == K
assertion.

Job 1/3 found strategy A (v1's merge-rank method, verbatim) beats B and C
at every K for both tokenizers and every model (see
bench/README-keepset-v3.md) -- so this script reuses
bench/rebuild-keepset-tokenizer.py's actual rebuild machinery (the same
functions bench/build-keepset-v2.py's Layer-1/3 emission reuses for its own
part of the pipeline) rather than reimplementing it, writing to
bench/keepsets-v3/ instead of bench/keepsets/ so v1's and v2's frozen
artifacts are never touched.
"""
import argparse
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
KEEPSETS_V3_ROOT = ROOT / "keepsets-v3"


def _load_module(name, filename):
    spec = importlib.util.spec_from_file_location(name, ROOT / filename)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


v3 = _load_module("build_keepset_v3_dep2", "build-keepset-v3.py")
vc = v3.vc
rk = v3.rk


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tokenizer", required=True)
    ap.add_argument("--tokenizer-label", required=True)
    ap.add_argument("--target-size", type=int, action="append", required=True)
    ap.add_argument("--optimum-note", default="", help="free text describing why this K was chosen, for provenance.md")
    return ap.parse_args()


def build_provenance_md(label, K, actual_K, coverage, script_sha, optimum_note):
    lines = []
    lines.append(f"# Provenance: keep-set v3 -- {label}-{actual_K}")
    lines.append("")
    lines.append(f"Generated by `bench/emit-keepset-v3.py` at script commit `{script_sha}`, using strategy "
                 "**A-fixed** (v1's merge-rank method, corrected -- see below).")
    lines.append("")
    lines.append("## Exact command line")
    lines.append("")
    lines.append("```")
    lines.append(f"python3 bench/emit-keepset-v3.py --tokenizer {coverage['tokenizer_path']} --tokenizer-label {label} --target-size {K}")
    lines.append("```")
    lines.append("")
    lines.append("## Selection method")
    lines.append("")
    lines.append(
        "Strategy A (merge-rank selection, `bench/vocab-coverage.py`'s `build_keep_set_for_tokenizer` + "
        "`final_keep_set_for_K`, v1's method verbatim: corpus-seen token ids from bench-data.json, "
        "bench-data-extended.json, pdf-pastes.json, arxiv-pastes.json, synth-spans.jsonl latex rows, "
        "unioned with byte alphabet + added/special tokens + webnn-workbench harness-prompt tokens + "
        "KaTeX macro seed + maths-English word seed, padded to K by ascending original token id) won "
        "the v3 fertility sweep at every K for both tokenizers, by a wide margin over strategies B and "
        "C (see `bench/README-keepset-v3.md`). But running the brief's Job 4 validation checks against "
        "pure strategy A found it FAILS check 1 for the Qwen3.5 tokenizer: it reproduces v1's own "
        "originally-reported failure (the 7 named LatexGen-prompt token ids, "
        "`bench/validate-keepset-v2.py`'s `QWEN35_FAILURE1_IDS`, are absent), because v1's corpus "
        "never included LatexGen's actual client prompt text (`public/pipeline.js` / "
        "`public/pdf-prompt.js`) -- only the webnn-workbench harness's separate, narrower prompt set. "
        "**A-fixed** = strategy A's exact base, unioned with the same LatexGen-prompt token layer B/C "
        "use (`bench/build-keepset-v2.py`'s `latexgen_and_harness_prompt_ids`, itself reusing "
        "`bench/build-keepset-seed-latexgen-prompts.py`'s seed, not re-derived), then BPE merge-"
        "ancestor-closed over the combined base (`bench/build-keepset-v2.py`'s "
        "`compute_merge_ancestor_closure`, reused) so no kept corpus/prompt token's producing merge "
        "rule gets silently dropped -- v1 never did this closure step at all, which is a real, "
        "independent defect (a corpus-seen multi-character token can still lose its OWN merge rule "
        "if an ancestor piece isn't independently kept), not specific to the prompt-token fix. "
        "Padded to K exactly like A, by ascending original token id. This is a minimal, justified "
        "patch to the winning strategy to pass the brief's own validation gate, not a re-tuned number: "
        "see `bench/README-keepset-v3.md`'s \"Job 4 validation\" section for the full before/after."
    )
    lines.append("")
    lines.append(f"## Why this K ({K})")
    lines.append("")
    lines.append(optimum_note)
    lines.append("")
    lines.append(f"- target K: {K}, actual size achieved: {actual_K}, clipped to natural: {coverage['clipped_to_natural']}")
    lines.append(f"- natural (no-padding) keep-set size for this tokenizer: {coverage['natural_keep_set_size']}")
    m = coverage["merges"]
    lines.append(f"- BPE merges: {m['before']} -> {m['after']} (dropped {m['dropped']}, {m['dropped_fraction']:.4f})")
    lc = coverage["length_check"]
    lines.append(f"- length check: expected K={lc['expected_K']}, tokenizers.Tokenizer.from_file={lc['tokenizers_from_file_len']}, "
                 f"transformers.AutoTokenizer.from_pretrained={lc['hf_autotokenizer_from_pretrained_len']}")
    v3f = coverage["v3_methodology_fertility"]
    lines.append(
        f"- v3-methodology fertility (426 held-out texts: 120 arxiv-pastes.json input+reference + "
        f"93 bench-data-extended.json ok items input+reference, real re-encode): "
        f"before={v3f['fertility_before_tokens_per_char']:.4f}, after={v3f['fertility_after_tokens_per_char']:.4f}, "
        f"inflation={v3f['fertility_inflation_relative']:+.4%}"
    )
    if coverage["stop_token_id_mismatches_found"]:
        lines.append(f"- stop_token_id mismatches found and corrected: {json.dumps(coverage['stop_token_id_mismatches_found'])}")
    lines.append("")
    lines.append(
        "See `SHA256SUMS.txt` in this directory for the authoritative, current SHA-256 of every "
        "emitted file (including this one)."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    args = parse_args()
    from tokenizers import Tokenizer
    from transformers import AutoTokenizer

    label = args.tokenizer_label
    built = v3.strategy_A_fixed_base(args.tokenizer)
    tok, tok_path = built["tok"], built["tok_path"]
    raw = json.loads(Path(tok_path).read_text())
    tok_dir = Path(tok_path).parent
    tok_cfg_path = tok_dir / "tokenizer_config.json"
    raw_cfg = json.loads(tok_cfg_path.read_text()) if tok_cfg_path.exists() else {}
    mlc_cfg_path = tok_dir / "mlc-chat-config.json"
    mlc_cfg = json.loads(mlc_cfg_path.read_text()) if mlc_cfg_path.exists() else {}

    full_str_to_old_id = dict(raw["model"]["vocab"])
    for e in raw["added_tokens"]:
        full_str_to_old_id[e["content"]] = e["id"]

    held_out_texts, held_out_meta = v3.held_out_texts()

    for K in args.target_size:
        final_keep, pad_ids, clipped = vc.final_keep_set_for_K(built, K)
        keep_idx = sorted(final_keep)
        new_id_map = {old: i for i, old in enumerate(keep_idx)}
        actual_K = len(keep_idx)

        new_raw, n_merges_before, n_merges_after, n_merges_dropped = rk.rebuild_tokenizer_json(raw, final_keep, new_id_map)
        surviving_strings = set(new_raw["model"]["vocab"].keys()) | {e["content"] for e in new_raw["added_tokens"]}
        new_cfg, n_phantom_dropped, n_extra_special_dropped = (
            rk.rebuild_tokenizer_config(raw_cfg, final_keep, new_id_map, surviving_strings) if raw_cfg else ({}, 0, 0)
        )
        special_tokens_map = rk.build_special_tokens_map(raw_cfg) if raw_cfg else {}

        new_conv_stop_ids, stop_id_mismatches = ([], [])
        if mlc_cfg:
            new_conv_stop_ids, stop_id_mismatches = rk.remap_stop_token_ids(
                mlc_cfg["conv_template"], full_str_to_old_id, new_id_map, final_keep
            )

        out_dir = KEEPSETS_V3_ROOT / f"{label}-{actual_K}"
        out_dir.mkdir(parents=True, exist_ok=True)

        (out_dir / "keep-idx.json").write_text(json.dumps(keep_idx) + "\n")
        (out_dir / "tokenizer.json").write_text(json.dumps(new_raw, ensure_ascii=False))
        if raw_cfg:
            (out_dir / "tokenizer_config.json").write_text(json.dumps(new_cfg, indent=2, ensure_ascii=False) + "\n")
        (out_dir / "special_tokens_map.json").write_text(json.dumps(special_tokens_map, indent=2, ensure_ascii=False) + "\n")

        config_patch = {
            "vocab_size": actual_K,
            "active_vocab_size": actual_K,
            "stop_token_ids": new_conv_stop_ids,
            "stop_token_ids_source_mismatches": stop_id_mismatches,
        }
        (out_dir / "config-patch.json").write_text(json.dumps(config_patch, indent=2) + "\n")

        new_tok = Tokenizer.from_str(json.dumps(new_raw))
        file_tok_len = Tokenizer.from_file(str(out_dir / "tokenizer.json")).get_vocab_size(with_added_tokens=True)
        hf_tok_len = len(AutoTokenizer.from_pretrained(str(out_dir)))
        length_check = {
            "expected_K": actual_K,
            "tokenizers_from_file_len": file_tok_len,
            "hf_autotokenizer_from_pretrained_len": hf_tok_len,
        }
        if file_tok_len != actual_K or hf_tok_len != actual_K:
            raise SystemExit(
                f"BUG: {out_dir} length check failed -- expected K={actual_K}, got "
                f"tokenizers.Tokenizer.from_file={file_tok_len}, transformers.AutoTokenizer.from_pretrained={hf_tok_len}"
            )

        v3_fert = v3.measure_fertility(tok, new_tok, held_out_texts)

        coverage = {
            "tokenizer_label": label,
            "tokenizer_path": tok_path,
            "keepset_version": "v3",
            "selection_strategy": "A-fixed (merge-rank, v1 verbatim, winner of the v3 sweep, "
                                   "plus the LatexGen-prompt layer + merge-ancestor closure -- see provenance.md)",
            "target_size": K,
            "actual_size": actual_K,
            "clipped_to_natural": clipped,
            "natural_keep_set_size": built["k_natural"],
            "merges": {
                "before": n_merges_before,
                "after": n_merges_after,
                "dropped": n_merges_dropped,
                "dropped_fraction": (n_merges_dropped / n_merges_before) if n_merges_before else 0.0,
            },
            "tokenizer_config_phantom_added_tokens_dropped": n_phantom_dropped,
            "tokenizer_config_extra_special_tokens_dropped": n_extra_special_dropped,
            "length_check": length_check,
            "v3_methodology_fertility": v3_fert,
            "v3_held_out_meta": held_out_meta,
            "stop_token_id_mismatches_found": stop_id_mismatches,
        }
        (out_dir / "coverage.json").write_text(json.dumps(coverage, indent=2) + "\n")

        script_sha = rk.git_head_sha()
        provenance_md = build_provenance_md(label, K, actual_K, coverage, script_sha, args.optimum_note)
        (out_dir / "provenance.md").write_text(provenance_md)

        files = ["keep-idx.json", "tokenizer.json", "special_tokens_map.json", "config-patch.json", "coverage.json", "provenance.md"]
        if raw_cfg:
            files.append("tokenizer_config.json")
        hashes = {f: rk.sha256_file(out_dir / f) for f in files}
        (out_dir / "SHA256SUMS.txt").write_text("\n".join(f"{h}  {f}" for f, h in hashes.items()) + "\n")

        print(f"=== v3 {label} K={K} -> actual={actual_K} ===")
        print(f"  natural={built['k_natural']} merges: {n_merges_before} -> {n_merges_after} (dropped {n_merges_dropped})")
        print(f"  length check: K={actual_K}, tokenizers={file_tok_len}, transformers={hf_tok_len}")
        print(f"  v3 fertility: before={v3_fert['fertility_before_tokens_per_char']:.4f} after={v3_fert['fertility_after_tokens_per_char']:.4f} inflation={v3_fert['fertility_inflation_relative']:+.4%}")
        for f, h in hashes.items():
            print(f"  {h}  {f}")
        print(f"  wrote {out_dir}")


if __name__ == "__main__":
    main()
