// Build the static (server-less) site into dist/.
//
// The static build is the on-device app and nothing else: no server tier, no
// Tab API, no compute mesh, and no model weights in the deploy (they are far
// past what a static host will serve, so they stream from a CDN instead).
// See docs/deploy.md.
import { cp, mkdir, rm, readFile, writeFile, readdir } from "node:fs/promises";
import { join } from "node:path";

const SRC = "public";
const OUT = "dist";

// Weights live in a Hugging Face repo; transformers.js asks for
// "<model>/onnx/<file>", so the template turns that into a path inside it.
const MODEL_REPO = process.env.MODEL_REPO ?? "ozhyhinas/latexgen-models";
const MODEL_REVISION = process.env.MODEL_REVISION ?? "main";

// Server-only or developer-only files that must not ship.
const EXCLUDE = new Set([
  "models",           // weights come from the CDN
  "bench.html", "bench.js", "bench-data.json",           // need api/bench
  "bench-images.html", "bench-images.js", "bench-images.json", "bench-images",
  "bench-runtime.html", "bench-runtime.js",
  "bench-load.html", "bench-load.js", "bench-fetch-patch.js",
]);

// Mirrors the CSP that server.js sends as a header; a static host cannot set
// headers, so it goes in a meta tag. frame-ancestors and HSTS have no meta
// equivalent — that is the one thing this build cannot enforce.
const CSP = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'",
  "worker-src 'self' blob:",
  "connect-src 'self' https:", // model weights stream from HuggingFace CDNs
  "img-src 'self' data: blob:",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self' data:",
  "form-action 'self' https://www.overleaf.com",
  "base-uri 'self'", "object-src 'none'",
].join("; ");

// A project page is served under a prefix, so a root-absolute asset path works
// locally and 404s in production. Catch that here rather than after deploying.
// Vendored libraries are excluded: they are checked in as shipped.
const ABSOLUTE = /(?:src|href)="\/|from\s+"\/|import\("\/|["'`]\/(?:vendor|models|icons|api)\//;
for (const entry of await readdir(SRC)) {
  if (!/\.(html|js|mjs|css|webmanifest)$/.test(entry)) continue;
  const text = await readFile(join(SRC, entry), "utf8");
  const lines = text.split("\n").map((l, i) => [i + 1, l]).filter(([, l]) => ABSOLUTE.test(l));
  if (lines.length) {
    throw new Error(`${entry}: root-absolute path breaks a prefixed deploy — make it relative\n` +
      lines.map(([n, l]) => `  ${entry}:${n}: ${l.trim().slice(0, 110)}`).join("\n"));
  }
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

for (const entry of await readdir(SRC)) {
  if (EXCLUDE.has(entry)) continue;
  await cp(join(SRC, entry), join(OUT, entry), { recursive: true });
}

// Graph-catalog entries (models/texo-webnn/, models/texify-webnn/,
// models/intellitex-webnn/) are small data, not weights: recipes, manifest,
// tokenizer. They ship with the site; the constants blobs do not, and are
// fetched from the URLs the entry's manifest names.
await cp(join(SRC, "models", "texo-webnn"), join(OUT, "models", "texo-webnn"), {
  recursive: true, filter: (src) => !src.endsWith(".bin"),
});
await cp(join(SRC, "models", "texify-webnn"), join(OUT, "models", "texify-webnn"), {
  recursive: true, filter: (src) => !src.endsWith(".bin"),
});
await cp(join(SRC, "models", "intellitex-webnn"), join(OUT, "models", "intellitex-webnn"), {
  recursive: true, filter: (src) => !src.endsWith(".bin"),
});

await writeFile(join(OUT, "config.js"), `// Generated by scripts/build-static.mjs — do not edit.
export const STATIC_BUILD = true;
export const MODEL_HOST = "https://huggingface.co/";
export const MODEL_PATH_TEMPLATE = "${MODEL_REPO}/resolve/${MODEL_REVISION}/{model}";
export const WEBNN_CATALOG_BASE = null;
`);

for (const entry of await readdir(OUT)) {
  if (!entry.endsWith(".html")) continue;
  const p = join(OUT, entry);
  const html = await readFile(p, "utf8");
  if (!html.includes("<head>")) throw new Error(`${entry}: no <head> to inject CSP into`);
  await writeFile(p, html.replace("<head>", `<head>\n  <meta http-equiv="content-security-policy" content="${CSP}">`));
}

// Stop GitHub Pages from running the output through Jekyll.
await writeFile(join(OUT, ".nojekyll"), "");

console.log(`built ${OUT}/ — weights from ${MODEL_HOST_LOG()}`);
function MODEL_HOST_LOG() { return `https://huggingface.co/${MODEL_REPO} @ ${MODEL_REVISION}`; }
